import type { Metadata } from 'next';
import { Anybody, Inter, Lexend } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--inter' });
const anybody = Anybody({ subsets: ['latin'], variable: '--anybody' });
const lexend = Lexend({ subsets: ['latin'], variable: '--lexend' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${anybody.variable} ${lexend.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
